# Lokaverkefni

### Útfærsla

In [1]:
import os
from pathlib import Path
import requests
import zipfile

DATA_DIR = Path("data")
ZIP_PATH = DATA_DIR / "IGC-News1-22.10.TEI.zip"
EXTRACT_DIR = DATA_DIR / "IGC-News1"

URL = "https://repository.clarin.is/repository/xmlui/bitstream/handle/20.500.12537/236/IGC-News1-22.10.TEI.zip"

DATA_DIR.mkdir(exist_ok=True)

def download_file(url: str, dest: Path):
    if dest.exists():
        print(f"File already exists: {dest}")
        return
    
    print(f"Downloading to {dest} ...")
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(dest, "wb") as f:
            for chunk in r.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    f.write(chunk)
    print("Download complete.")

def unzip_file(zip_path: Path, extract_dir: Path):
    if extract_dir.exists() and any(extract_dir.iterdir()):
        print(f"Already extracted: {extract_dir}")
        return
    
    print(f"Extracting {zip_path} to {extract_dir} ...")
    extract_dir.mkdir(exist_ok=True)
    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(extract_dir)
    print("Extraction complete.")

download_file(URL, ZIP_PATH)
unzip_file(ZIP_PATH, EXTRACT_DIR)

File already exists: data\IGC-News1-22.10.TEI.zip
Already extracted: data\IGC-News1

In [2]:
from pathlib import Path
import xml.etree.ElementTree as ET



def local_name(tag):
    """
    Cleans the local name of a XML tag by removing namespace
    """
    return tag.split("}", 1)[-1] if "}" in tag else tag

def parse_article(article_path: Path):
    """
    Parse an article XML file and extract pertinent fields needed for the assignment
    """
    tree = ET.parse(article_path)
    root = tree.getroot()

    title = None
    source = None
    article_date = None
    keywords = []
    paragraphs = []

    # Go through all elements in the XML tree
    for elem in root.iter():
        name = local_name(elem.tag)

        # The "analytic" element contains article metadata
        if name == "analytic":
            for child in elem:
                child_name = local_name(child.tag)

                # Extract the first article title found
                if child_name == "title" and child.text and not title:
                    title = child.text.strip()

                # Extract the article date from the "when" attribute
                elif child_name == "date" and child.attrib.get("when") and not article_date:
                    article_date = child.attrib["when"]
                    
        # The "monogr" element contains source metadata
        elif name == "monogr":
            for child in elem:

                # Extract the source name (i.e the newspapers name)
                if local_name(child.tag) == "title" and child.text and not source:
                    source = child.text.strip()
                    
        #The "term" elements contain the keywords/category tags
        elif name == "term" and elem.text:
            keywords.append(elem.text.strip())

    # Extract only the real article text from the body section
    for body in root.iter():
        if local_name(body.tag) == "body":
            for elem in body.iter():
                if local_name(elem.tag) == "p" and elem.text:
                    text = elem.text.strip()
                    if text:
                        paragraphs.append(text)

    return {
        "path": str(article_path),
        "title": title,
        "source": source,
        "date": article_date,
        "keywords": keywords,
        "text": "\n".join(paragraphs)
    }

In [3]:
from pathlib import Path
import xml.etree.ElementTree as ET


# Limit dataset to articles from Vísir in 2020
SOURCE = "visir"
YEAR = "2020"


# Path to the main XML wrapper file for the selected source.
wrapper_path = Path(f"data/IGC-News1/IGC-News1-22.10.TEI/{SOURCE}/IGC-News1-{SOURCE}-22.10.xml")

# Parse the wrapper XML file
tree = ET.parse(wrapper_path)
root = tree.getroot()


# Get the paths to all article XML files
hrefs = [
    elem.attrib["href"]
    for elem in root.iter()
    if elem.tag.endswith("include")
]

# Keep only article references from the selected year.
hrefs_year = [
    h for h in hrefs
    if h.startswith(f"{YEAR}/")
]

# Print status information about the number of articles found
print("Total articles:", len(hrefs))
print(f"Articles in {YEAR}:", len(hrefs_year))
print("First 5:", hrefs_year[:5])

Total articles: 699957
Articles in 2020: 37213
First 5: ['2020/01/IGC-News1-visir_7266555.xml', '2020/01/IGC-News1-visir_7266556.xml', '2020/01/IGC-News1-visir_7266557.xml', '2020/01/IGC-News1-visir_7266558.xml', '2020/01/IGC-News1-visir_7266559.xml']

In [4]:
sample_articles = []

# Parse the first 5000 articles from the selected year
for href in hrefs_year[:5000]:
    article_path = wrapper_path.parent / href
    try:
        sample_articles.append(parse_article(article_path))
    except Exception as e:
        print("Failed:", article_path, e)

# Show how many articles were successfully parsed and print first article
print("Parsed:", len(sample_articles))
sample_articles[0]

Parsed: 5000

{'path': 'data\\IGC-News1\\IGC-News1-22.10.TEI\\visir\\2020\\01\\IGC-News1-visir_7266555.xml',
 'title': '„Dæmigert janúarveður“ næstu daga - Vísir',
 'source': 'Vísir',
 'date': '2020-01-01',
 'keywords': ['Innlent', 'Fréttir'],
 'text': 'Árið byrjar með úrkomu víða um land og er spáð skúrum eða slydduéljum. Þó ert bjart með köflum norðaustantil og heldur þurrt. Hiti hefur fallið frá því á gamlársdag og verður á bilinu 0 til 6 stig á landinu í dag.\nÞá kólnar á morgun og er spáð snjókomu eða éljum víða á landinu, einkum fyrir norðan. Kalt heimskautaloft færist yfir landið og fellur hiti talsvert. Um kvöldið lægir og rofar til á sunnanverðu landinu en spáð frosti í öllum landshlutum á bilinu 3 til 10 stig.\nÞetta kemur fram í hugleiðingum veðurfræðings hjá Veðurstofu Íslands þar sem segir einnig að dagarnir á eftir séu órólegir. Landsmenn megi búast við „dæmigerðu janúarveðri“ með lægðagangi og umhleypingum. Sólin sé hins vegar farin að hækka á lofti og dagarnir farnir að lengjast.\nVeðurhorfur á landinu næstu daga\nÁ föstudag:\nNorðvestan 13-20 m/s, en talsvert hægari SV- og V-lands. Snjókoma eða él N-til á landinu, en léttskýjað sunnan heiða. Frost 2 til 10 stig. Lægir og rofar til um kvöldið.\nÁ laugardag:\nGengur í hvassa suðaustanátt með snjókomu og síðar slyddu eða rigningu. Hlýnandi veður. Suðvestlægari og skúrir eða slydduél um kvöldið, en léttir til NA-lands.\nÁ sunnudag:\nSuðvestan 10-18 m/s. Bjartviðri A-lands, annars skúrir eða él. Hiti um eða yfir frostmarki. Lægir um kvöldið.\nÁ mánudag:\nNorðvestlæg átt með slyddu eða rigningu og síðar snjókomu á A-verðu landinu, en éljum V-til. Kólnandi veður.\nÁ þriðjudag:\nÚtlit fyrir suðvestanátt með éljum S- og V-lands.'}

In [5]:
from collections import Counter

#Info on most common keywords
keyword_counts = Counter()

for article in sample_articles:
    keyword_counts.update(article["keywords"])

print("Most common keywords:")
for keyword, count in keyword_counts.most_common(50):
    print(keyword, count)

#Sanity checks to make sure files have been properly parsed
print("\nFirst parsed article:")
article = sample_articles[0]

for k, v in article.items():
    print(f"{k}: {v if k != 'text' else v[:500]}")
    print()

Most common keywords:
Fréttir 2205
Íþróttir 1678
Innlent 1378
Fótbolti 712
Erlendar fréttir 669
Handbolti 430
Mannlíf 396
Körfubolti 308
Viðskipti 263
Viðhorf 186
Menning 83
Fótbolti - Ísland 65
Atvinnulíf 53
Kynning 39
Bílar 35
Tónlist 31
Bíó og sjónvarp 23
Golf 17
Veiði 16
Lífsstíll 15
Skopmyndir 11
Tölvuleikir 7
Tíska 7
Gagnrýni 6
óflokkað 5
Matur og drykkur 3

First parsed article:
path: data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\01\IGC-News1-visir_7266555.xml

title: „Dæmigert janúarveður“ næstu daga - Vísir

source: Vísir

date: 2020-01-01

keywords: ['Innlent', 'Fréttir']

text: Árið byrjar með úrkomu víða um land og er spáð skúrum eða slydduéljum. Þó ert bjart með köflum norðaustantil og heldur þurrt. Hiti hefur fallið frá því á gamlársdag og verður á bilinu 0 til 6 stig á landinu í dag.
Þá kólnar á morgun og er spáð snjókomu eða éljum víða á landinu, einkum fyrir norðan. Kalt heimskautaloft færist yfir landið og fellur hiti talsvert. Um kvöldið lægir og rofar til á sunnanverðu landinu en spáð frosti í öllum landshlutum á bilinu 3 til 10 stig.
Þetta kemur fram í huglei

In [6]:
import pandas as pd

# Conveert category labels to non icelandic characters
TARGET_LABELS = {
    "Íþróttir": "ithrottir",
    "Innlent": "innlent",
    "Erlendar fréttir": "erlent",
    "Viðskipti": "vidskipti",
    "Mannlíf": "mannlif",
    "Menning": "menning",
}

def choose_label(keywords):
    """
    filters out articles with multiple categories to make dataset simpler
    """
    matches = []

    # Check each keyword from the article
    for keyword in keywords:
        if keyword in TARGET_LABELS:
            matches.append(TARGET_LABELS[keyword])

    # Only use articles with exactly one label that is in target labels
    if len(matches) == 1:
        return matches[0]
    
    return None

In [7]:
rows = []

# Go through all parsed articles
for article in sample_articles:

    # Choose a label based on the category
    label = choose_label(article["keywords"])

    # Skip articles that more or less than one label
    if label is None:
        continue

    # Skip empty or short articles
    if not article["text"] or len(article["text"].split()) < 30:
        continue

    # Add the article to the dataset
    rows.append({
        "title": article["title"],
        "text": article["text"],
        "label": label,
        "keywords": article["keywords"],
        "source": article["source"],
        "date": article["date"],
        "path": article["path"],
    })

# Convert the list of articles into a pandas df
df = pd.DataFrame(rows)

print(df.shape)
print(df["label"].value_counts())
df.head()

(4465, 7)
label
ithrottir    1678
innlent      1378
erlent        669
mannlif       394
vidskipti     263
menning        83
Name: count, dtype: int64

,title,text,label,keywords,source,date,path
0,„Dæmigert janúarveður“ næstu daga - Vísir,Árið byrjar með úrkomu víða um land og er spáð...,innlent,"[Innlent, Fréttir]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...
1,Icelandair og FVFÍ undirrita kjarasamning - Vísir,Icelandair og Flugvirkjafélag Íslands hafa end...,innlent,"[Innlent, Fréttir]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...
2,Árni Oddur sæmdur riddarakrossi - Vísir,Fjórtán Íslendingar voru sæmdir heiðursmerki h...,innlent,"[Innlent, Fréttir]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...
3,Lektor sem var sagt upp við HR kennir við HÍ -...,"Kristinn Sigurjónsson, fyrrverandi lektor ið H...",innlent,"[Innlent, Fréttir]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...
4,54 ára bið á enda og nú með leikmenn á borð vi...,Vissel Kobe hefur loksins unnið til verðlauna ...,ithrottir,"[Íþróttir, Fótbolti]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...

In [8]:
# keep only articles with labels that have enough data and are clear enough
GOOD_LABELS = ["ithrottir", "innlent", "erlent", "mannlif"]
df_small = df[df["label"].isin(GOOD_LABELS)].copy()

print(df_small.shape)
print(df_small["label"].value_counts())
df_small.head()

(4119, 7)
label
ithrottir    1678
innlent      1378
erlent        669
mannlif       394
Name: count, dtype: int64

,title,text,label,keywords,source,date,path
0,„Dæmigert janúarveður“ næstu daga - Vísir,Árið byrjar með úrkomu víða um land og er spáð...,innlent,"[Innlent, Fréttir]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...
1,Icelandair og FVFÍ undirrita kjarasamning - Vísir,Icelandair og Flugvirkjafélag Íslands hafa end...,innlent,"[Innlent, Fréttir]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...
2,Árni Oddur sæmdur riddarakrossi - Vísir,Fjórtán Íslendingar voru sæmdir heiðursmerki h...,innlent,"[Innlent, Fréttir]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...
3,Lektor sem var sagt upp við HR kennir við HÍ -...,"Kristinn Sigurjónsson, fyrrverandi lektor ið H...",innlent,"[Innlent, Fréttir]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...
4,54 ára bið á enda og nú með leikmenn á borð vi...,Vissel Kobe hefur loksins unnið til verðlauna ...,ithrottir,"[Íþróttir, Fótbolti]",Vísir,2020-01-01,data\IGC-News1\IGC-News1-22.10.TEI\visir\2020\...

In [9]:
from sklearn.model_selection import train_test_split

X = df_small["text"]
y = df_small["label"]

#Splits the dataset into a training set and a test set.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2, # Use 20% of the data for testing
    random_state=42,
    stratify=y # Keep the same label distribution in train/test
)

print("Train size:", len(X_train))
print("Test size:", len(X_test))

print("\nTrain label counts:")
print(y_train.value_counts())

print("\nTest label counts:")
print(y_test.value_counts())

Train size: 3295
Test size: 824

Train label counts:
label
ithrottir    1342
innlent      1103
erlent        535
mannlif       315
Name: count, dtype: int64

Test label counts:
label
ithrottir    336
innlent      275
erlent       134
mannlif       79
Name: count, dtype: int64

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

In [11]:
# Create a TF-IDF vectorizer 
vectorizer = TfidfVectorizer(
    lowercase=True,      
    max_features=20000,  
    ngram_range=(1, 2),  
    min_df=2             
)

# Learn the vocabulary from the training data and vectorize it
X_train_vec = vectorizer.fit_transform(X_train)

# Vectorize the test
X_test_vec = vectorizer.transform(X_test)

# Create a Logistic Regression classifier
model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

# Train the model on the training data
model.fit(X_train_vec, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [12]:
import re
from collections import Counter
import numpy as np

def tokenize(text):
    """
    Convert text into a list of cleaned word tokens.
    Lowercases the text, removes punctuation and symbols, splits text into words
    """
    text = text.lower()
    text = re.sub(r"[^a-záéíóúýþæöð0-9\s]", " ", text)
    return text.split()

In [13]:
MAX_FEATURES = 20000
MIN_COUNT = 2

# Count word frequencies in the training texts
word_counts = Counter()

for text in X_train:
    tokens = tokenize(text)
    word_counts.update(tokens)

# Build a vocabulary from the most common words
vocab = {}

for word, count in word_counts.most_common(MAX_FEATURES):
    if count >= MIN_COUNT:
        vocab[word] = len(vocab)

print("Vocabulary size:", len(vocab))
list(vocab.items())[:20]

Vocabulary size: 20000

[('í', 0),
 ('að', 1),
 ('og', 2),
 ('á', 3),
 ('sem', 4),
 ('er', 5),
 ('við', 6),
 ('það', 7),
 ('en', 8),
 ('til', 9),
 ('var', 10),
 ('um', 11),
 ('með', 12),
 ('ekki', 13),
 ('hann', 14),
 ('fyrir', 15),
 ('því', 16),
 ('af', 17),
 ('hefur', 18),
 ('ég', 19)]

In [14]:
def vectorize_texts(texts, vocab):
    """
    Convert texts vectors using the given vocabulary via bag of words.
    
    Each row is one article.
    Each column is one word from the vocabulary.
    Each value is how often that word appears in the article.
    """
    #init empty matrix with one row per text and one column per vocabulary word
    X_vec = np.zeros((len(texts), len(vocab)))

    #iterate over each articel
    for i, text in enumerate(texts):

        #tokenize and clean
        tokens = tokenize(text)

        #count token if in vocabulary
        for token in tokens:
            if token in vocab:
                # Get the column index for the token
                j = vocab[token]
                # update count by one for this word in the article
                X_vec[i, j] += 1
                
    return X_vec

# MUNA AÐ KLÁRA DOCUMENTATION FYRIR FALLIÐ

In [15]:
y_pred = model.predict(X_test_vec)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Macro F1:", f1_score(y_test, y_pred, average="macro"))
print("Micro F1:", f1_score(y_test, y_pred, average="micro"))

print("\nClassification report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.9356796116504854
Macro F1: 0.904726627603003
Micro F1: 0.9356796116504854

Classification report:
              precision    recall  f1-score   support

      erlent       0.93      0.96      0.95       134
     innlent       0.94      0.93      0.94       275
   ithrottir       0.98      0.96      0.97       336
     mannlif       0.74      0.78      0.76        79

    accuracy                           0.94       824
   macro avg       0.90      0.91      0.90       824
weighted avg       0.94      0.94      0.94       824

In [16]:
import pandas as pd

labels = sorted(df_small["label"].unique())

cm = confusion_matrix(y_test, y_pred, labels=labels)

cm_df = pd.DataFrame(
    cm,
    index=[f"true_{label}" for label in labels],
    columns=[f"pred_{label}" for label in labels]
)

cm_df

                pred_erlent  pred_innlent  pred_ithrottir  pred_mannlif
true_erlent             129             4               0             1
true_innlent              4           257               1            13
true_ithrottir            1             4             323             8
true_mannlif              4             7               6            62

In [17]:
X_train_custom = vectorize_texts(X_train, vocab)
X_test_custom = vectorize_texts(X_test, vocab)

print(X_train_custom.shape)
print(X_test_custom.shape)

(3295, 20000)
(824, 20000)

In [18]:
# Create a logistic regression model for the custom bag of words vectors
custom_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

# Train the model
custom_model.fit(X_train_custom, y_train)

# Predict labels for the test articles
y_pred_custom = custom_model.predict(X_test_custom)

print("Custom BoW Accuracy:", accuracy_score(y_test, y_pred_custom))
print("Custom BoW Macro F1:", f1_score(y_test, y_pred_custom, average="macro"))
print("Custom BoW Micro F1:", f1_score(y_test, y_pred_custom, average="micro"))

print("\nClassification report:")
print(classification_report(y_test, y_pred_custom))

Custom BoW Accuracy: 0.9296116504854369
Custom BoW Macro F1: 0.8964637525699473
Custom BoW Micro F1: 0.9296116504854369

Classification report:
              precision    recall  f1-score   support

      erlent       0.90      0.92      0.91       134
     innlent       0.93      0.93      0.93       275
   ithrottir       0.96      0.98      0.97       336
     mannlif       0.82      0.73      0.77        79

    accuracy                           0.93       824
   macro avg       0.90      0.89      0.90       824
weighted avg       0.93      0.93      0.93       824

In [19]:
comparison = pd.DataFrame([
    {
        "Model": "sklearn TF-IDF + Logistic Regression",
        "Accuracy": accuracy_score(y_test, y_pred),
        "Macro F1": f1_score(y_test, y_pred, average="macro"),
        "Micro F1": f1_score(y_test, y_pred, average="micro"),
    },
    {
        "Model": "Custom Bag-of-Words + Logistic Regression",
        "Accuracy": accuracy_score(y_test, y_pred_custom),
        "Macro F1": f1_score(y_test, y_pred_custom, average="macro"),
        "Micro F1": f1_score(y_test, y_pred_custom, average="micro"),
    }
])

comparison

                                       Model  Accuracy  Macro F1  Micro F1
0       sklearn TF-IDF + Logistic Regression  0.935680  0.904727  0.935680
1  Custom Bag-of-Words + Logistic Regression  0.929612  0.896464  0.929612

In [20]:
import numpy as np

class CustomLogisticRegression:
    """
    Custom implementation of multiclass Logistic Regression.
    """
    def __init__(self, learning_rate=0.1, epochs=300, reg_strength=0.001):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.reg_strength = reg_strength
        self.W = None
        self.b = None
        self.classes_ = None

    def softmax(self, z):
        """
        Convert raw class scores into probabilities.
        """
        z = z - np.max(z, axis=1, keepdims=True)
        exp_z = np.exp(z)
        return exp_z / np.sum(exp_z, axis=1, keepdims=True)

    def one_hot(self, y):
        """
        Convert labels into one hot encoded lists.
        Example:
            classes = [erlent, innlent, ithrottir, mannlif]
            label = ithrottir
            one-hot = [0, 0, 1, 0]
        """
        y_encoded = np.zeros((len(y), len(self.classes_)))

        for i, label in enumerate(y):
            class_index = np.where(self.classes_ == label)[0][0]
            y_encoded[i, class_index] = 1

        return y_encoded

    def fit(self, X, y):
        """
        Train the model using gradient descent.

        """

        y = np.array(y)
        self.classes_ = np.unique(y)

        n_samples, n_features = X.shape
        n_classes = len(self.classes_)

        # Initialize weights and biases with zeros
        # W has one column per class
        self.W = np.zeros((n_features, n_classes))

        # b has one bias value per class
        self.b = np.zeros((1, n_classes))

        # Convert labels to one hot
        y_onehot = self.one_hot(y)

        # Train for the the selected epochs
        for epoch in range(self.epochs):

            # Calculate raw class scores: z = XW + b
            scores = X @ self.W + self.b

            # Convert raw scores into probabilities
            probs = self.softmax(scores)

            # calculate error 
            error = probs - y_onehot

            # Gradient of the loss with respect to weights
            dW = (X.T @ error) / n_samples

            # Gradient of the loss with respect to biases
            db = np.mean(error, axis=0, keepdims=True)

            # L2 regularization to reduce overfitting
            dW += self.reg_strength * self.W

            # Update weights and biases using gradient descent
            self.W -= self.learning_rate * dW
            self.b -= self.learning_rate * db



    def predict_proba(self, X):
        """
        Predict class probabilities for new articles.
        """
        # Calculate raw class scores
        scores = X @ self.W + self.b

        # Convert scores into probabilities
        return self.softmax(scores)

    def predict(self, X):
        """
        Predict the most likely class for each article.
        """

        # Get class probabilities
        probs = self.predict_proba(X)

        # Choose the class with the highest probability
        class_indices = np.argmax(probs, axis=1)

        # Convert back to label names
        return self.classes_[class_indices]

In [21]:
#Init class of the custom logistic regression implementation
custom_classifier = CustomLogisticRegression(
    learning_rate=0.1,
    epochs=300,
    reg_strength=0.001
)

custom_classifier.fit(X_train_custom, y_train)

y_pred_from_scratch = custom_classifier.predict(X_test_custom)

print("Custom Vectorizer + Custom Classifier Accuracy:",
      accuracy_score(y_test, y_pred_from_scratch))

print("Custom Vectorizer + Custom Classifier Macro F1:",
      f1_score(y_test, y_pred_from_scratch, average="macro"))

print("Custom Vectorizer + Custom Classifier Micro F1:",
      f1_score(y_test, y_pred_from_scratch, average="micro"))

print("\nClassification report:")
print(classification_report(y_test, y_pred_from_scratch))

Custom Vectorizer + Custom Classifier Accuracy: 0.9174757281553398
Custom Vectorizer + Custom Classifier Macro F1: 0.8792024530279564
Custom Vectorizer + Custom Classifier Micro F1: 0.9174757281553398

Classification report:
              precision    recall  f1-score   support

      erlent       0.91      0.88      0.89       134
     innlent       0.91      0.94      0.92       275
   ithrottir       0.96      0.97      0.96       336
     mannlif       0.79      0.70      0.74        79

    accuracy                           0.92       824
   macro avg       0.89      0.87      0.88       824
weighted avg       0.92      0.92      0.92       824

In [23]:
labels = sorted(df_small["label"].unique())

cm_scratch = confusion_matrix(
    y_test,
    y_pred_from_scratch,
    labels=labels
)

cm_scratch_df = pd.DataFrame(
    cm_scratch,
    index=[f"true_{label}" for label in labels],
    columns=[f"pred_{label}" for label in labels]
)

cm_scratch_df

                pred_erlent  pred_innlent  pred_ithrottir  pred_mannlif
true_erlent             118            14               1             1
true_innlent              5           258               3             9
true_ithrottir            3             3             325             5
true_mannlif              4             9              11            55

In [22]:
comparison = pd.DataFrame([
    {
        "Model": "sklearn TF-IDF + sklearn Logistic Regression",
        "Accuracy": accuracy_score(y_test, y_pred),
        "Macro F1": f1_score(y_test, y_pred, average="macro"),
        "Micro F1": f1_score(y_test, y_pred, average="micro"),
    },
    {
        "Model": "Custom Bag-of-Words + sklearn Logistic Regression",
        "Accuracy": accuracy_score(y_test, y_pred_custom),
        "Macro F1": f1_score(y_test, y_pred_custom, average="macro"),
        "Micro F1": f1_score(y_test, y_pred_custom, average="micro"),
    },
    {
        "Model": "Custom Bag-of-Words + custom Logistic Regression",
        "Accuracy": accuracy_score(y_test, y_pred_from_scratch),
        "Macro F1": f1_score(y_test, y_pred_from_scratch, average="macro"),
        "Micro F1": f1_score(y_test, y_pred_from_scratch, average="micro"),
    }
])

comparison

,Model,Accuracy,Macro F1,Micro F1
0,sklearn TF-IDF + sklearn Logistic Regression,0.935680,0.904727,0.935680
1,Custom Bag-of-Words + sklearn Logistic Regression,0.929612,0.896464,0.929612
2,Custom Bag-of-Words + custom Logistic Regression,0.917476,0.879202,0.917476